// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smwdhpusnqxjxvapnlmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtd2RocHVzbnF4anh2YXBubG1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0OTcwNTEsImV4cCI6MjA2NjA3MzA1MX0.pbUfSZM8E7JShpgrg9CmN4WzxdXr58z2wkUco0vw5XA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);